# This is a basic workflow to help you get started with Actions

name: BingDwn

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  schedule:
    - cron: '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #- name: Url Request Steps
      #  run: curl -i https://api.day.app/${{ secrets.BARK_ID }}/推送内容的fs
        
      - name: File Test
        run: |
          cd ${{ github.workspace }}/temp
          cat tt
          
      - name: File Commmit
        run: |
          [ ! -d bing_img  ] && mkdir bing_img
          cd bing_img
          date_str=`date +%Y%m%d`
          img_description=`curl -X GET 'https://www.bing.com/HPImageArchive.aspx?n=1&idx=0&format=js'`
          echo $img_description >> bing_img.info
          img_url=`echo $img_description | grep -P '(?<="url":")[^",]+' -o`
          full_img_url='https://www.bing.com'$img_url
          curl -o $date_str.jpg $full_img_url
          echo -e > bing_img.info
          git config user.name cccMing
          git config user.email john_ming@outlook.com
          git add .
          git commit -m "commit $date_str"
          git push
      # date > generated.txt 这个是写入文件测试，要git之前

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
